#dev
instance_id: i-067a66f67ad8a7b60

# nginx
server_name: dev.timesmanager.app
app_port: 8080

# app
app_name: timesmanager
app_user: ec2-user
app_group: ec2-user
app_dir: /opt/timesmanager
app_jar_path: /opt/timesmanager/timesmanager.jar
java_path: /usr/bin/java
spring_profile: dev

# env
aws_region: ap-northeast-1
dynamodb_table_name: timesmanager_dev
server_port: 8080