- name: Install Cloudwatch Agent
  dnf:
    name: amazon-cloudwatch-agent
    state: present

- name: Create CloudWatch Agent config directory
  file:
    path: /opt/aws/amazon-cloudwatch-agent/etc
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy CloudWatch Agent config
  template:
    src: amazon-cloudwatch-agent.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: "0644"
  notify: Restart cloudwatch agent
