- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart app
  ansible.builtin.systemd:
    name: timesmanager
    state: restarted
    enabled: true

- name: Restart cloudwatch agent
  command: >
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
    -a fetch-config
    -m ec2
    -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json