- name: Install Java Corretto 21
  dnf:
    name: java-21-amazon-corretto
    state: present

- name: Create CloudWatch Agent config directory
  file:
    path: /opt/aws/amazon-cloudwatch-agent/etc
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install Cloudwatch Agent
  dnf:
    name: amazon-cloudwatch-agent
    state: present

- name: Deploy CloudWatch Agent config
  template:
    src: amazon-cloudwatch-agent.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: "0644"
  notify: Restart cloudwatch agent

- name: Create app directory
  file:
    path: /opt/timesmanager
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "0755"

- name: Deploy app env file
  template:
    src: env.j2
    dest: "{{ app_dir }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0600"
  notify: Restart app

- name: Copy systemd unit
  template:
    src: timesmanager.service.j2
    dest: /etc/systemd/system/timesmanager.service
  notify: Reload systemd

