name: Deploy Spring Boot App to EC2_Dev

on:
  push:
    branches:
      - feature
      - develop
    paths:
      - 'springboot/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Public IP Install
      id: ip
      uses: haythem/public-ip@v1.3

    - name: AWS CLI install
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: AWS set Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: gradle clean build -x test
      working-directory: ./springboot/timesmanager-backend

    - name: Open SSH security group
      run: |
        # SSHのセキュリティグループを開放する
        aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Copy jar file to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST_DEV }}
        username: ${{ secrets.EC2_USER_DEV }}
        key: ${{ secrets.EC2_KEY_DEV }}
        source: springboot/timesmanager-backend/build/libs/timesmanager.jar
        target: /opt/timesmanager
        overwrite: true
        strip_components: 4

    - name: SSH and restart app
      uses: appleboy/ssh-action@v1.0.0
      continue-on-error: true
      with:
        host: ${{ secrets.EC2_HOST_DEV }}
        username: ${{ secrets.EC2_USER_DEV }}
        key: ${{ secrets.EC2_KEY_DEV }}
        script_stop: true
        script: |
          set -e
          ls -l /opt/timesmanager
          sudo systemctl restart timesmanager.service
          sudo systemctl status timesmanager.service --no-pager

    - name: edit security group
      if: always()
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Notify to Slack
      if: always()
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          MESSAGE="✅ timesmanager-backend デプロイ完了（branch: ${{ github.ref_name }}）"
        else
          MESSAGE="❌ timesmanager-backend デプロイ失敗（branch: ${{ github.ref_name }}）"
        fi

        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"${MESSAGE}\"}" \
          ${{ secrets.SLACK_WEBHOOK }}