spring:
  application:
    name: timesmanager

aws:
  dynamodb:
    region: ${AWS_REGION:ap-northeast-1}
    tableName: ${DYNAMODB_TABLE_NAME:timesmanager_dev}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: DEBUG